# Site settings
title: Documentation
email: manossef@gmail.com
description: >
  Documentation for the Mbed SDK
baseurl:  "mbed-sdk"
project-name: "mbed-sdk"
github_username:  Pithikos

# Build settings
markdown: kramdown
