# Site settings
title: "Mbed SDK"
github_project-name:  "mbed-sdk"
github_username:  Pithikos
email: manossef@gmail.com
baseurl: ""

# Build settings
markdown: kramdown
permalink: /:title

# Default front matter for all posts
defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "post"
      title: "no-title"

# Custom configuration
filenames:
  new_file: "tempname"
